# Form implementation generated from reading ui file '.\UI\calibration_ui.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 582)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.analysis_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.analysis_button.setGeometry(QtCore.QRect(180, 160, 151, 71))
        self.analysis_button.setObjectName("analysis_button")
        self.yn_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.yn_widget.setGeometry(QtCore.QRect(330, 240, 301, 301))
        self.yn_widget.setObjectName("yn_widget")
        self.analysis_status_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.analysis_status_label.setGeometry(QtCore.QRect(340, 160, 161, 71))
        self.analysis_status_label.setText("")
        self.analysis_status_label.setObjectName("analysis_status_label")
        self.analysis_counter_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.analysis_counter_label.setGeometry(QtCore.QRect(510, 160, 281, 71))
        self.analysis_counter_label.setText("")
        self.analysis_counter_label.setObjectName("analysis_counter_label")
        self.prev_orig_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.prev_orig_button.setGeometry(QtCore.QRect(640, 240, 71, 71))
        self.prev_orig_button.setObjectName("prev_orig_button")
        self.next_orig_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.next_orig_button.setGeometry(QtCore.QRect(720, 240, 71, 71))
        self.next_orig_button.setObjectName("next_orig_button")
        self.xn_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.xn_widget.setGeometry(QtCore.QRect(20, 240, 301, 301))
        self.xn_widget.setObjectName("xn_widget")
        self.discard_orig_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.discard_orig_button.setGeometry(QtCore.QRect(640, 320, 151, 61))
        self.discard_orig_button.setText("")
        self.discard_orig_button.setObjectName("discard_orig_button")
        self.current_orig_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.current_orig_label.setGeometry(QtCore.QRect(640, 390, 151, 71))
        self.current_orig_label.setText("")
        self.current_orig_label.setObjectName("current_orig_label")
        self.kept_orig_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.kept_orig_label.setGeometry(QtCore.QRect(640, 470, 151, 71))
        self.kept_orig_label.setText("")
        self.kept_orig_label.setObjectName("kept_orig_label")
        self.browse_file_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.browse_file_button.setGeometry(QtCore.QRect(20, 160, 151, 71))
        self.browse_file_button.setObjectName("browse_file_button")
        self.filename_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.filename_label.setGeometry(QtCore.QRect(20, 110, 771, 41))
        self.filename_label.setText("")
        self.filename_label.setObjectName("filename_label")
        self.file_title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.file_title_label.setGeometry(QtCore.QRect(20, 80, 121, 31))
        self.file_title_label.setObjectName("file_title_label")
        self.dir_title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.dir_title_label.setGeometry(QtCore.QRect(20, 10, 121, 31))
        self.dir_title_label.setObjectName("dir_title_label")
        self.dir_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.dir_label.setGeometry(QtCore.QRect(20, 40, 771, 41))
        self.dir_label.setText("")
        self.dir_label.setObjectName("dir_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.analysis_button.setText(_translate("MainWindow", "Analize\n"
"dataset"))
        self.prev_orig_button.setText(_translate("MainWindow", "Previous\n"
"origami"))
        self.next_orig_button.setText(_translate("MainWindow", "Next\n"
"origami"))
        self.browse_file_button.setText(_translate("MainWindow", "Browse\n"
"file (.hdf5)"))
        self.file_title_label.setText(_translate("MainWindow", "Calibration file name:"))
        self.dir_title_label.setText(_translate("MainWindow", "Calibration file directory"))
